### ISSUE TITLE
[Vue warn]: Unknown custom element: <vueterminal> - did you register the component correctly?

### ISSUE THREAD

**Issue by ndabAP** [shershen08/vue-terminal-ui#4]
Demo doesn't work at all.

**Comment by shershen08** [comment]
I'll check that and get back to you

**Comment by shershen08** [comment]
Did you add VueTerminal to your components section?
```
components: {
    VueTerminal
  }
```
Which bundler do you use ? with a vue-cli basic webpack template everything works fine

**Comment by shershen08** [comment]
fixed the link to demo - https://github.com/shershen08/vue-terminal-ui/commit/5355a2f4c16466647ce429891bc7a4c639012de0
