### ISSUE TITLE
Can't get command arguments

### ISSUE THREAD

**Issue by amitlevy21** [shershen08/vue-terminal-ui#6]
Hi! Thank you so much for sharing vue-terminal-ui!

I am using the `onCliCommand (data, resolve, reject)` method to get the typed command and execute accordingly however it does not contain the whole command in the `data` var.

For example, if i type into the terminal `echo -e hello` then i get the following:
![image](https://user-images.githubusercontent.com/28672915/60822728-b6840e80-a1ae-11e9-9f93-4a607c26958b.png)

How can i get the entire command including the options (-e) and arguments (hello) ? 

Here is my code:
```vue
<template>
  <div>
    <h1>Terminal</h1>
    <app-terminal
      intro="intro"
      console-sign="$"
      allow-arbitrary
      height="500px"
      @command="onCliCommand"
    />
  </div>
</template>

<script>
import VueTerminal from "vue-terminal-ui";

export default {
  components: {
    'app-terminal': VueTerminal
  },
  methods: {
      onCliCommand (data, resolve, reject) {
        console.log(data)
        resolve('')
      }
  }
};
</script>

<style>
</style>

```

**Comment by shershen08** [comment]
Thanks for reporting this, @amitlevy21 indeed I see the problem
I'll update a version asap

**Comment by shershen08** [comment]
please try newer version vue-terminal-ui@0.1.6
